<?php

namespace Database\Seeders;

use App\Models\s_category;
use App\Models\s_sub_category;
use App\Models\s_sub_subcat1;
use App\Models\s_sub_subcat2;
use App\Models\s_sub_subcat3;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShopManuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        s_category::create(['name' => 'ENDODONTICS']);
        s_category::create(['name' => 'GENERAL DENTISTRY']);
        s_category::create(['name' => 'Consumables']);
        s_category::create(['name' => 'ORTHO STORE']);
        s_category::create(['name' => 'INSTRUMENTS']);
        s_category::create(['name' => 'EQUIPMENTS']);
        s_category::create(['name' => 'MORE']);


        s_sub_category::create(['cat_id' => 1,'name'=> 'ACCESS CAVITY PREPARATION']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'CLEAR']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'SHAPE']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'OBTURATE']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'POST & CORE']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'RC IRRIGANTS & ROOT REPAIR']);
        s_sub_category::create(['cat_id' => 1,'name'=> 'ENDODONTIC ACCESSORIES']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'IMPRESSION MATERIALS']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'RESTORATIVES']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'BONDING AGENTS']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'CROWN & BRIDGE']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'X-RAYS']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'PREVENTIVE']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'FINISHING & POLISHING']);
        s_sub_category::create(['cat_id' => 2,'name'=> 'ESTHETIC & COSMETIC']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'GLOVE STORE']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'INFECTIVE CONTROL']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'Protective Gear']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'GENERAL ACCESSORIES']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'FACE MASKS & CAPS']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'TREATMENT AIDS']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'TREATMENT AREA PREPARATION']);
        s_sub_category::create(['cat_id' => 3,'name'=> 'GENERAL DISPOSABLES']);
        s_sub_category::create(['cat_id' => 4,'name'=> 'CONVENTIONAL BRACES']);
        s_sub_category::create(['cat_id' => 4,'name'=> 'NEW AGE BRACES']);
        s_sub_category::create(['cat_id' => 4,'name'=> 'ANCHORAGE']);
        s_sub_category::create(['cat_id' => 4,'name'=> 'ARCHWIRES & ELASTICS']);
        s_sub_category::create(['cat_id' => 4,'name'=> 'ORTHO ACCESSORIES']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'GENERAL INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'ORTHO INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'ENDO INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'PERIO INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'SURGIAL INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 5,'name'=> 'PROSTHO INSTRUMENTS']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'DENTAL CHAIRS & ACCESSORIES']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'GENERAL EQUIPMENTS']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'SMALL EQUIPMENTS']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'DENTAL HANDPIECES']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'ENDODONTIC EQUIPMENTS']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'STERILIZATION EQUIPMENT']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'IMAGING SYSTEMS']);
        s_sub_category::create(['cat_id' => 6,'name'=> 'OTHER EQUIPMENT']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'IMPLANTS']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'ORAL CARE']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'PROSTHODONTICS']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'PERIODONTICS']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'PAEDODONTICS']);
        s_sub_category::create(['cat_id' => 7,'name'=> 'ORAL & MAXILLOFACIAL SURGERY']);

        s_sub_subcat1::create(['sub_cat_id' => 1,  'name' =>'Endodontic Burs']);
        s_sub_subcat1::create(['sub_cat_id' => 2,  'name' =>'Pulp Devitalization']);
        s_sub_subcat1::create(['sub_cat_id' => 2,  'name' =>'Barbed Broaches']);
        s_sub_subcat1::create(['sub_cat_id' => 2,  'name' =>'Re-treatment']);
        s_sub_subcat1::create(['sub_cat_id' => 3,  'name' =>'Endodontic Files']);
        s_sub_subcat1::create(['sub_cat_id' => 4,  'name' =>'Gutta Percha Points']);
        s_sub_subcat1::create(['sub_cat_id' => 4,  'name' =>'Paper  Points']);
        s_sub_subcat1::create(['sub_cat_id' => 4,  'name' =>'Root Canal Sealants']);
        s_sub_subcat1::create(['sub_cat_id' => 4,  'name' =>'Spreaders & Pluggers']);
        s_sub_subcat1::create(['sub_cat_id' => 5,  'name' =>'Posts & Drills']);
        s_sub_subcat1::create(['sub_cat_id' => 5,  'name' =>'Core Build-Up Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 5,  'name' =>'Peeso Reamers']);
        s_sub_subcat1::create(['sub_cat_id' => 6,  'name' =>'Root Canal Irrigants']);
        s_sub_subcat1::create(['sub_cat_id' => 6,  'name' =>'Root Repair']);
        s_sub_subcat1::create(['sub_cat_id' => 7,  'name' =>'Sedative dressing']);
        s_sub_subcat1::create(['sub_cat_id' => 8,  'name' =>'The Putty Store']);
        s_sub_subcat1::create(['sub_cat_id' => 8,  'name' =>'Alginate']);
        s_sub_subcat1::create(['sub_cat_id' => 8,  'name' =>'Impression Compounds']);
        s_sub_subcat1::create(['sub_cat_id' => 8,  'name' =>'Bite Registration']);
        s_sub_subcat1::create(['sub_cat_id' => 8,  'name' =>'Impression Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Restorative Kits Store']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Composites']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Glass Ionomers']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Amalgams']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Pupl Protection']);
        s_sub_subcat1::create(['sub_cat_id' => 9,  'name' =>'Other Restoratives']);
        s_sub_subcat1::create(['sub_cat_id' => 10, 'name' => 'Self Etch Adhesives']);
        s_sub_subcat1::create(['sub_cat_id' => 10, 'name' => 'Total Etch Adhesives']);
        s_sub_subcat1::create(['sub_cat_id' => 10, 'name' => 'Dental Cements']);
        s_sub_subcat1::create(['sub_cat_id' => 11, 'name' => 'Tooth Preparation Burs']);
        s_sub_subcat1::create(['sub_cat_id' => 11, 'name' => 'Temporisation']);
        s_sub_subcat1::create(['sub_cat_id' => 11, 'name' => 'Luting Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 11, 'name' => 'C&B Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 12, 'name' => 'X-ray Films']);
        s_sub_subcat1::create(['sub_cat_id' => 12, 'name' => 'X-ray Developers & Fixers']);
        s_sub_subcat1::create(['sub_cat_id' => 12, 'name' => 'X-ray Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 13, 'name' => 'Fluoridation']);
        s_sub_subcat1::create(['sub_cat_id' => 13, 'name' => 'Pit & Fissure Sealants']);
        s_sub_subcat1::create(['sub_cat_id' => 13, 'name' => 'Caries Detectors/Control']);
        s_sub_subcat1::create(['sub_cat_id' => 14, 'name' => 'Opaquers & Tints']);
        s_sub_subcat1::create(['sub_cat_id' => 14, 'name' => 'Polishing Brushes/Kits']);
        s_sub_subcat1::create(['sub_cat_id' => 14, 'name' => 'Polishing Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 14, 'name' => 'Finishing Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 14, 'name' => 'Restorative Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 15, 'name' => 'Bleaching']);
        s_sub_subcat1::create(['sub_cat_id' => 15, 'name' => 'Tooth cleaning & Polishing ']);
        s_sub_subcat1::create(['sub_cat_id' => 15, 'name' => 'Tooth Jewellery']);
        s_sub_subcat1::create(['sub_cat_id' => 16, 'name' => 'Powerered Latex']);
        s_sub_subcat1::create(['sub_cat_id' => 16, 'name' => 'Power-free Latex']);
        s_sub_subcat1::create(['sub_cat_id' => 16, 'name' => 'Nitrile Gloves']);
        s_sub_subcat1::create(['sub_cat_id' => 16, 'name' => 'Surgical Gloves']);
        s_sub_subcat1::create(['sub_cat_id' => 17, 'name' => 'Sterillization Products']);
        s_sub_subcat1::create(['sub_cat_id' => 17, 'name' => 'Instrument Diisinfectants']);
        s_sub_subcat1::create(['sub_cat_id' => 17, 'name' => 'Surface Disinfectants']);
        s_sub_subcat1::create(['sub_cat_id' => 17, 'name' => 'Hand hygiene']);
        s_sub_subcat1::create(['sub_cat_id' => 18, 'name' => 'Patient Protection']);
        s_sub_subcat1::create(['sub_cat_id' => 18, 'name' => 'Doctor Protection']);
        s_sub_subcat1::create(['sub_cat_id' => 18, 'name' => 'Face Protection']);
        s_sub_subcat1::create(['sub_cat_id' => 19, 'name' => 'Surgical accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 19, 'name' => 'Denture & Retainer Boxes']);
        s_sub_subcat1::create(['sub_cat_id' => 19, 'name' => 'Mixing & Dispensing']);
        s_sub_subcat1::create(['sub_cat_id' => 19, 'name' => 'Other General accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 19, 'name' => 'Prostho Accossories']);
        s_sub_subcat1::create(['sub_cat_id' => 20, 'name' => '3-Ply Disposable Masks']);
        s_sub_subcat1::create(['sub_cat_id' => 20, 'name' => 'Special Masks']);
        s_sub_subcat1::create(['sub_cat_id' => 20, 'name' => 'Head Caps']);
        s_sub_subcat1::create(['sub_cat_id' => 21, 'name' => 'Saliva Ejectors']);
        s_sub_subcat1::create(['sub_cat_id' => 21, 'name' => 'Mirrors & Probes']);
        s_sub_subcat1::create(['sub_cat_id' => 21, 'name' => 'Set-up Trays & Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 21, 'name' => 'Study']);
        s_sub_subcat1::create(['sub_cat_id' => 22, 'name' => 'Cheek Guards & Retractors']);
        s_sub_subcat1::create(['sub_cat_id' => 22, 'name' => 'Dental Dams & Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 22, 'name' => 'Matrix Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 23, 'name' => 'Cotton Products & Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 24, 'name' => 'Metal']);
        s_sub_subcat1::create(['sub_cat_id' => 24, 'name' => 'Cosmetic']);
        s_sub_subcat1::create(['sub_cat_id' => 25, 'name' => 'Self-ligating']);
        s_sub_subcat1::create(['sub_cat_id' => 25, 'name' => 'Aligners']);
        s_sub_subcat1::create(['sub_cat_id' => 25, 'name' => 'Lingual']);
        s_sub_subcat1::create(['sub_cat_id' => 26, 'name' => 'Bands & Attachments']);
        s_sub_subcat1::create(['sub_cat_id' => 26, 'name' => 'Buccal Tubes']);
        s_sub_subcat1::create(['sub_cat_id' => 26, 'name' => 'TADs']);
        s_sub_subcat1::create(['sub_cat_id' => 26, 'name' => 'Orthopedic Appliances']);
        s_sub_subcat1::create(['sub_cat_id' => 27, 'name' => 'Archwires']);
        s_sub_subcat1::create(['sub_cat_id' => 27, 'name' => 'Ligature Wires']);
        s_sub_subcat1::create(['sub_cat_id' => 27, 'name' => 'Elastics']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Retainer Materials']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Relief waxes']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Adhesives']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Expansion Screws & Springs']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Lingual Attachments']);
        s_sub_subcat1::create(['sub_cat_id' => 28, 'name' => 'Other accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 29, 'name' => 'Diagnostic Instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 29, 'name' => 'Instrument Kits & Cassettes']);
        s_sub_subcat1::create(['sub_cat_id' => 29, 'name' => 'Miscellaneous']);
        s_sub_subcat1::create(['sub_cat_id' => 30, 'name' => 'Ortho Pliers']);
        s_sub_subcat1::create(['sub_cat_id' => 30, 'name' => 'bracket positioning']);
        s_sub_subcat1::create(['sub_cat_id' => 30, 'name' => 'Wire Cutters']);
        s_sub_subcat1::create(['sub_cat_id' => 30, 'name' => 'Band Seaters']);
        s_sub_subcat1::create(['sub_cat_id' => 30, 'name' => 'Other Ortho instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 31, 'name' => 'Operative Dentistry']);
        s_sub_subcat1::create(['sub_cat_id' => 31, 'name' => 'RCT instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 31, 'name' => 'Rubber Dam Instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Scalers']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Curettes']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Periodontal Probes']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Periodontal Files']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'knives']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Elevators']);
        s_sub_subcat1::create(['sub_cat_id' => 32, 'name' => 'Other Perio instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Scalpels & Scissors']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Needle Holders & Hemostats']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Forceps']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Elevators & Retractors']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Bone Cutting instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Surgical burs']);
        s_sub_subcat1::create(['sub_cat_id' => 33, 'name' => 'Other Surgical Instruments']);
        s_sub_subcat1::create(['sub_cat_id' => 34, 'name' => 'Carvers & knives']);
        s_sub_subcat1::create(['sub_cat_id' => 34, 'name' => 'Crown Removers']);
        s_sub_subcat1::create(['sub_cat_id' => 34, 'name' => 'Cord Packers']);
        s_sub_subcat1::create(['sub_cat_id' => 34, 'name' => 'Mixing Spatulas']);
        s_sub_subcat1::create(['sub_cat_id' => 34, 'name' => 'Articulators']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Dental Chairs']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Dental Stools']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Compressors']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Suuction units']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Extra Oral Suction units']);
        s_sub_subcat1::create(['sub_cat_id' => 35, 'name' => 'Chair accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 36, 'name' => 'Bleaching & Whitening units']);
        s_sub_subcat1::create(['sub_cat_id' => 36, 'name' => 'Mixers & Dispensers']);
        s_sub_subcat1::create(['sub_cat_id' => 36, 'name' => 'Ultrasonic Scelers']);
        s_sub_subcat1::create(['sub_cat_id' => 36, 'name' => 'Amalgamators']);
        s_sub_subcat1::create(['sub_cat_id' => 36, 'name' => 'Air Polishing Units']);
        s_sub_subcat1::create(['sub_cat_id' => 37, 'name' => 'Light Cure Units']);
        s_sub_subcat1::create(['sub_cat_id' => 37, 'name' => 'Intra Oral Cameras']);
        s_sub_subcat1::create(['sub_cat_id' => 37, 'name' => 'Loupes & Magnifiers']);
        s_sub_subcat1::create(['sub_cat_id' => 37, 'name' => 'hand Sanitizer Dispensers']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'High speed handpieces']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'Low speed handpieces']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'Airotor Cartridges']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'handpiece Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'Micromotors']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'Endo handpieces']);
        s_sub_subcat1::create(['sub_cat_id' => 38, 'name' => 'implant handpieces']);
        s_sub_subcat1::create(['sub_cat_id' => 39, 'name' => 'Apex Locators']);
        s_sub_subcat1::create(['sub_cat_id' => 39, 'name' => 'Endomotors']);
        s_sub_subcat1::create(['sub_cat_id' => 39, 'name' => 'Obturation Systems']);
        s_sub_subcat1::create(['sub_cat_id' => 39, 'name' => 'Other Endo Equipment']);
        s_sub_subcat1::create(['sub_cat_id' => 39, 'name' => 'Endomotors with Apex locators']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'Dental Autoclaves']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'Ultrasonic Cleaners']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'UV Cabinets']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'Water Distillers']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'Glass bead Sterillizers']);
        s_sub_subcat1::create(['sub_cat_id' => 40, 'name' => 'Other Sterillizers']);
        s_sub_subcat1::create(['sub_cat_id' => 41, 'name' => 'Radiovisiography (RVG)']);
        s_sub_subcat1::create(['sub_cat_id' => 41, 'name' => 'X-ray units']);
        s_sub_subcat1::create(['sub_cat_id' => 41, 'name' => 'X-ray processors & Viewers']);
        s_sub_subcat1::create(['sub_cat_id' => 42, 'name' => 'Surgical Equipment']);
        s_sub_subcat1::create(['sub_cat_id' => 42, 'name' => 'Dental Lasers']);
        s_sub_subcat1::create(['sub_cat_id' => 42, 'name' => 'Laboratory Equipment']);
        s_sub_subcat1::create(['sub_cat_id' => 42, 'name' => 'Other Dental equipment']);
        s_sub_subcat1::create(['sub_cat_id' => 43, 'name' => 'Dental Implants']);
        s_sub_subcat1::create(['sub_cat_id' => 43, 'name' => 'Implant Drills']);
        s_sub_subcat1::create(['sub_cat_id' => 43, 'name' => 'Implant Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 43, 'name' => 'Implant Abutments']);
        s_sub_subcat1::create(['sub_cat_id' => 44, 'name' => 'Toothbrushes & Toothpastes']);
        s_sub_subcat1::create(['sub_cat_id' => 44, 'name' => 'Interdental Cleaning']);
        s_sub_subcat1::create(['sub_cat_id' => 44, 'name' => 'Flossing']);
        s_sub_subcat1::create(['sub_cat_id' => 44, 'name' => 'Clinical products']);
        s_sub_subcat1::create(['sub_cat_id' => 45, 'name' => 'Denture relines']);
        s_sub_subcat1::create(['sub_cat_id' => 45, 'name' => 'Model Creation']);
        s_sub_subcat1::create(['sub_cat_id' => 45, 'name' => 'Acrylics']);
        s_sub_subcat1::create(['sub_cat_id' => 45, 'name' => 'Dental waxes']);
        s_sub_subcat1::create(['sub_cat_id' => 45, 'name' => 'Denture processing']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Surgical products']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Surgical dressings']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Tissue Management']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Bone grafts']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Plaque Control']);
        s_sub_subcat1::create(['sub_cat_id' => 46, 'name' => 'Splints & mouth Guards']);
        s_sub_subcat1::create(['sub_cat_id' => 47, 'name' => 'Pediatric Crowns']);
        s_sub_subcat1::create(['sub_cat_id' => 47, 'name' => 'Pulp Therapy']);
        s_sub_subcat1::create(['sub_cat_id' => 47, 'name' => 'Pedodontic Files']);
        s_sub_subcat1::create(['sub_cat_id' => 47, 'name' => 'Pedodontic Accessories']);
        s_sub_subcat1::create(['sub_cat_id' => 48, 'name' => 'Local Anaesthetics']);
        s_sub_subcat1::create(['sub_cat_id' => 48, 'name' => 'Post Extraction Dressing']);
        s_sub_subcat1::create(['sub_cat_id' => 48, 'name' => 'Surgical Accessories']);


        s_sub_subcat2::create(['sub_subcat1_id' => 1, 'name' => 'Carbide Burs']);
        s_sub_subcat2::create(['sub_subcat1_id' => 1, 'name' => 'Diamond Burs']);
        s_sub_subcat2::create(['sub_subcat1_id' => 4, 'name' => 'GP Solvents']);
        s_sub_subcat2::create(['sub_subcat1_id' => 4, 'name' => 'GP Removers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 5, 'name' => 'NiTi Rotary Files']);
        s_sub_subcat2::create(['sub_subcat1_id' => 5, 'name' => 'NiTi Hand Files']);
        s_sub_subcat2::create(['sub_subcat1_id' => 5, 'name' => 'K Files']);
        s_sub_subcat2::create(['sub_subcat1_id' => 5, 'name' => 'H Files']);
        s_sub_subcat2::create(['sub_subcat1_id' => 5, 'name' => 'Other Endo files']);
        s_sub_subcat2::create(['sub_subcat1_id' => 10, 'name' => 'Metal Post']);
        s_sub_subcat2::create(['sub_subcat1_id' => 10, 'name' => 'Fiber Post']);
        s_sub_subcat2::create(['sub_subcat1_id' => 13, 'name' => 'EDTA']);
        s_sub_subcat2::create(['sub_subcat1_id' => 13, 'name' => 'Antibacterial & tissue dissolvers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 20, 'name' => 'Impression Trays']);
        s_sub_subcat2::create(['sub_subcat1_id' => 20, 'name' => 'Tray Adhesives']);
        s_sub_subcat2::create(['sub_subcat1_id' => 20, 'name' => 'Tissue Retraction']);
        s_sub_subcat2::create(['sub_subcat1_id' => 20, 'name' => 'Custom tray Fabrication']);
        s_sub_subcat2::create(['sub_subcat1_id' => 22, 'name' => 'Packable']);
        s_sub_subcat2::create(['sub_subcat1_id' => 22, 'name' => 'Universal']);
        s_sub_subcat2::create(['sub_subcat1_id' => 22, 'name' => 'Flowable']);
        s_sub_subcat2::create(['sub_subcat1_id' => 28, 'name' => 'Etchants']);
        s_sub_subcat2::create(['sub_subcat1_id' => 28, 'name' => 'Adhesives']);
        s_sub_subcat2::create(['sub_subcat1_id' => 29, 'name' => 'Glass Ionomer Cements']);
        s_sub_subcat2::create(['sub_subcat1_id' => 29, 'name' => 'Resin Cements']);
        s_sub_subcat2::create(['sub_subcat1_id' => 29, 'name' => 'Temporay Cements']);
        s_sub_subcat2::create(['sub_subcat1_id' => 29, 'name' => 'Luting Cements']);
        s_sub_subcat2::create(['sub_subcat1_id' => 32, 'name' => 'Temporary luting']);
        s_sub_subcat2::create(['sub_subcat1_id' => 32, 'name' => 'Permanent Luting ']);
        s_sub_subcat2::create(['sub_subcat1_id' => 32, 'name' => 'Primers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 35, 'name' => 'Developers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 35, 'name' => 'Fixers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 37, 'name' => 'Fluoride Gels & trays']);
        s_sub_subcat2::create(['sub_subcat1_id' => 37, 'name' => 'Fluoride Varnishes']);
        s_sub_subcat2::create(['sub_subcat1_id' => 45, 'name' => 'In Office Bleaching']);
        s_sub_subcat2::create(['sub_subcat1_id' => 45, 'name' => 'At home bleaching']);
        s_sub_subcat2::create(['sub_subcat1_id' => 52, 'name' => 'Sterillization Rills & Pouches']);
        s_sub_subcat2::create(['sub_subcat1_id' => 52, 'name' => 'Sterillization Rills & Pouches']);
        s_sub_subcat2::create(['sub_subcat1_id' => 58, 'name' => 'Hand Sanitizers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 59, 'name' => 'patient Bibs/Drapes']);
        s_sub_subcat2::create(['sub_subcat1_id' => 60, 'name' => 'Doctor Coats']);
        s_sub_subcat2::create(['sub_subcat1_id' => 60, 'name' => 'Shoe Covers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 61, 'name' => 'Eyewears']);
        s_sub_subcat2::create(['sub_subcat1_id' => 61, 'name' => 'Face Shields']);
        s_sub_subcat2::create(['sub_subcat1_id' => 62, 'name' => 'Suture Needles & Threads']);
        s_sub_subcat2::create(['sub_subcat1_id' => 62, 'name' => 'Disposable Syringes & Tips']);
        s_sub_subcat2::create(['sub_subcat1_id' => 64, 'name' => 'Mixing Tips']);
        s_sub_subcat2::create(['sub_subcat1_id' => 64, 'name' => 'Mixing Accessories']);
        s_sub_subcat2::create(['sub_subcat1_id' => 64, 'name' => 'Applicator Tips & Brushes']);
        s_sub_subcat2::create(['sub_subcat1_id' => 73, 'name' => 'Patient Education Models']);
        s_sub_subcat2::create(['sub_subcat1_id' => 73, 'name' => 'Practice Models']);
        s_sub_subcat2::create(['sub_subcat1_id' => 73, 'name' => 'Patient Education Posters']);
        s_sub_subcat2::create(['sub_subcat1_id' => 77, 'name' => 'Cotton accessories']);
        s_sub_subcat2::create(['sub_subcat1_id' => 77, 'name' => 'Cotton Products']);
        s_sub_subcat2::create(['sub_subcat1_id' => 78, 'name' => 'Traditional']);
        s_sub_subcat2::create(['sub_subcat1_id' => 78, 'name' => 'Mini-Twin']);
        s_sub_subcat2::create(['sub_subcat1_id' => 78, 'name' => 'Low Profile']);
        s_sub_subcat2::create(['sub_subcat1_id' => 79, 'name' => 'Ceramic']);
        s_sub_subcat2::create(['sub_subcat1_id' => 79, 'name' => 'Others']);
        s_sub_subcat2::create(['sub_subcat1_id' => 80, 'name' => 'Metal']);
        s_sub_subcat2::create(['sub_subcat1_id' => 80, 'name' => 'Clear']);
        s_sub_subcat2::create(['sub_subcat1_id' => 80, 'name' => 'Low profile']);
        s_sub_subcat2::create(['sub_subcat1_id' => 87, 'name' => 'Nickel Titanium']);
        s_sub_subcat2::create(['sub_subcat1_id' => 87, 'name' => 'Stainless Steel']);
        s_sub_subcat2::create(['sub_subcat1_id' => 89, 'name' => 'Ligature ties']);
        s_sub_subcat2::create(['sub_subcat1_id' => 89, 'name' => 'Separators']);
        s_sub_subcat2::create(['sub_subcat1_id' => 89, 'name' => 'E Chains']);
        s_sub_subcat2::create(['sub_subcat1_id' => 89, 'name' => 'Ortho Elastics']);
        s_sub_subcat2::create(['sub_subcat1_id' => 96, 'name' => 'Mirrors']);
        s_sub_subcat2::create(['sub_subcat1_id' => 96, 'name' => 'Probes']);
        s_sub_subcat2::create(['sub_subcat1_id' => 96, 'name' => 'Tweezers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 96, 'name' => 'PMT kits']);
        s_sub_subcat2::create(['sub_subcat1_id' => 104, 'name' => 'Hand Cutting Instruments']);
        s_sub_subcat2::create(['sub_subcat1_id' => 104, 'name' => 'Rotary Cutting Instruments']);
        s_sub_subcat2::create(['sub_subcat1_id' => 104, 'name' => 'Filling Instruments']);
        s_sub_subcat2::create(['sub_subcat1_id' => 104, 'name' => 'Composite Instruments']);
        s_sub_subcat2::create(['sub_subcat1_id' => 162, 'name' => 'Dental Implant Equipment']);
        s_sub_subcat2::create(['sub_subcat1_id' => 162, 'name' => 'Physiodispensers']);
        s_sub_subcat2::create(['sub_subcat1_id' => 179, 'name' => 'Astringents/Hemostatics']);


        s_sub_subcat3::create(['sub_subcat2_id' => 1, 'name' => 'Endo Access Burs']);
        s_sub_subcat3::create(['sub_subcat2_id' => 1, 'name' => 'HP Series Burs']);
        s_sub_subcat3::create(['sub_subcat2_id' => 1, 'name' => 'RA Series Burs']);
        s_sub_subcat3::create(['sub_subcat2_id' => 7, 'name' => 'NiTi K files']);

    }
}
